CREATE TYPE "JewelryType" AS ENUM (
  'SILVER_RING',
  'SILVER_BRACELET',
  'SILVER_NECKLACE',
  'SILVER_PENDANT',
  'SILVER_CHARM',
  'SILVER_EARRINGS',
  'GOLD_JEWELRY',
  'GLASSES',
  'LEATHER_CRAFT',
  'OTHER_ACCESSORY'
);

ALTER TABLE "Jewelry"
ADD COLUMN "type" "JewelryType" NOT NULL DEFAULT 'SILVER_RING';

CREATE INDEX "Jewelry_type_idx" ON "Jewelry"("type");
